// increment operator 
Integer x = 10;
x++;
System.debug(x); // 11

// addition assignment operator
x += 5; // same as using x = x + 5;
System.debug(x); // 16

// subtraction assignment operator
x -= 4; // same as using x = x - 4;
System.debug(x); // 12

// multiplication assignment operator
x *= 2; // same as using x = x * 2;
System.debug(x); // 24

// division assignment operator
x /= 3; // same as using x = x / 3;
System.debug(x); // 8