Boolean amIadult = true;
System.debug(amIadult);

String greeting = 'Hello World!';
System.debug(greeting);

integer year = 2024;
System.debug(year);

Long centibillions = 20000000000L;
System.debug(centibillions);

Decimal milk_price = 8.24;
System.debug(milk_price);

Double whatsapp_pp = 200000.5;
System.debug(whatsapp_pp);

Date birthday = Date.newInstance(2024, 6, 8);
System.debug(birthday);

Time afternoon = Time.newInstance(15, 5, 10, 7);
System.debug(afternoon);

Datetime birthday_afternoon = Datetime.newInstance(birthday, afternoon);
System.debug(birthday_afternoon);
